#!/usr/bin/env ruby

require 'gtk3'

app = Gtk::Application.new 'com.regularpoe.opiate', :flags_none

app.signal_connect :activate do |application|
    window = Gtk::ApplicationWindow.new(application)
    window.set_title 'opiate'
    window.present
end

puts app.run